// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {variableincome} from '../models';
import {desktop} from '../models';

export function Create(arg1:variableincome.CreateVariableIncomeDto):Promise<desktop.ErrorResponse>;
